apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/ingress-nginx/overlays/prod
  - ../../apps/frontend/overlays/prod
  - ../../apps/backend/overlays/prod
